version: '3.8'
services:
  userservice:
    build: .
    ports:
      - "8972:8972"
    environment:
      - DB_USERNAME=user
      - DB_PASSWORD=password
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5471/userservice
    depends_on:
      - postgres

  postgres:
    image: postgres:15
    ports:
      - "5471:5471"
    environment:
      - POSTGRES_DB=userservice
      - POSTGRES_USER=user
      - POSTGRES_PASSWORD=password
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: